name: Run unit test with go test

on:
  pull_request:
    types:
      - opened
      - synchronize
  push:
    branches:
      - "**"

jobs:
  test:
    name: Unit Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-go@v4
        with:
          go-version: "1.22"

      - name: Run Tests
        run: go test ./...
